import { createReducer, on } from '@ngrx/store';
import { createSite } from './sites.action';
import { Site } from '../../model/site';

const initialState: Site[] = [
  {
    id: 1,
    organisation: 'GreenTech Solutions',
    siteName: 'Solar Plant A',
    ownerName: 'Rohit Kumar',
    contact: 9876543210,
    email: 'rohit@greentech.com',
    address: 'Sector 21 Industrial Area',
    city: 'Chandigarh',
    district: 'Chandigarh',
    state: 'Chandigarh',
    pin: 160022,
  },
  {
    id: 2,
    organisation: 'EcoBuild Corp',
    siteName: 'Eco Factory Unit 4',
    ownerName: 'Amarjeet Singh',
    contact: 9123456780,
    email: 'amarjeet@ecobuild.com',
    address: 'Phase 7 Industrial Zone',
    city: 'Mohali',
    district: 'SAS Nagar',
    state: 'Punjab',
    pin: 140307,
  },
  {
    id: 3,
    organisation: 'AgroFresh Pvt Ltd',
    siteName: 'Cold Storage Plant',
    ownerName: 'Simran Kaur',
    contact: 9001234567,
    email: 'simran@agrofresh.com',
    address: 'Mandi Road',
    city: 'Ludhiana',
    district: 'Ludhiana',
    state: 'Punjab',
    pin: 141001,
  },
  {
    id: 4,
    organisation: 'MetalWorks Industries',
    siteName: 'Foundry Unit',
    ownerName: 'Harpreet Singh',
    contact: 9988776655,
    email: 'harpreet@metalworks.com',
    address: 'Industrial Area B',
    city: 'Ludhiana',
    district: 'Ludhiana',
    state: 'Punjab',
    pin: 141003,
  },
  {
    id: 5,
    organisation: 'GreenLife Farms',
    siteName: 'Greenhouse Block 2',
    ownerName: 'Neha Sharma',
    contact: 9090909090,
    email: 'neha@greenlife.com',
    address: 'Rural Belt',
    city: 'Amritsar',
    district: 'Amritsar',
    state: 'Punjab',
    pin: 143001,
  },
  {
    id: 6,
    organisation: 'SkyNet Engineering',
    siteName: 'Assembly Unit',
    ownerName: 'Rajat Verma',
    contact: 9812345678,
    email: 'rajat@skynetengg.com',
    address: 'Electronic City',
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pin: 560100,
  },
  {
    id: 7,
    organisation: 'BioCare Labs',
    siteName: 'Testing Facility',
    ownerName: 'Pooja Yadav',
    contact: 9753124680,
    email: 'pooja@biocare.com',
    address: 'Ring Road',
    city: 'Indore',
    district: 'Indore',
    state: 'Madhya Pradesh',
    pin: 452001,
  },
  {
    id: 8,
    organisation: 'TechNova Pvt Ltd',
    siteName: 'R&D Center',
    ownerName: 'Anuj Gupta',
    contact: 9797979797,
    email: 'anuj@technova.com',
    address: 'Hi-Tech Park',
    city: 'Hyderabad',
    district: 'Ranga Reddy',
    state: 'Telangana',
    pin: 500032,
  },
  {
    id: 9,
    organisation: 'Urban Water Solutions',
    siteName: 'Water Treatment Plant',
    ownerName: 'Tanya Khurana',
    contact: 9034567890,
    email: 'tanya@urbanwater.com',
    address: 'Sector 15',
    city: 'Gurugram',
    district: 'Gurugram',
    state: 'Haryana',
    pin: 122001,
  },
  {
    id: 10,
    organisation: 'SteelCore Industries',
    siteName: 'Rolling Mill',
    ownerName: 'Vikram Chauhan',
    contact: 9823456712,
    email: 'vikram@steelcore.com',
    address: 'Railway Road',
    city: 'Jalandhar',
    district: 'Jalandhar',
    state: 'Punjab',
    pin: 144001,
  },
];

// export const initialState: Site[] = [];

export const siteReducer = createReducer(
  initialState,
  on(createSite, (state, action) => {
    return [action.site, ...state];
  })
);
